stages:
  - lint
  - build
  - test

# image: nixos/nix:2.18.0

ruff:
  stage: lint
  script:
    - nix build .#checks.x86_64-linux.ruff

treefmt:
  stage: lint
  script:
    - nix build .#checks.x86_64-linux.treefmt

build-pflotran:
  stage: build
  script:
    - nix build .#pflotran

flake-checks:
  stage: test
  script:
    - nix build .#checks.x86_64-linux.check_h5_file
